"""esquema inicial: vehiculos, leads y simulaciones

Revision ID: 9c1f6de89bbc
Revises: 
Create Date: 2026-08-29 23:55:41.966291
"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op



revision: str = '9c1f6de89bbc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('COMPRA', 'VENTA', 'FINANCIACION', 'RETOMA', 'SEGUROS', 'TRAMITES', 'CONSIGNACION', 'CONTACTO', name='tipolead'), nullable=False),
    sa.Column('estado', sa.Enum('NUEVO', 'CONTACTADO', 'EN_PROCESO', 'GANADO', 'PERDIDO', name='estadolead'), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=160), nullable=True),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
    sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vehiculo_slug', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=True),
    sa.Column('datos', sa.JSON(), nullable=True),
    sa.Column('origen_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('utm', sa.JSON(), nullable=True),
    sa.Column('acepta_politica_datos', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_telefono'), ['telefono'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_vehiculo_slug'), ['vehiculo_slug'], unique=False)

    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('linea', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('kilometraje', sa.Integer(), nullable=False),
    sa.Column('transmision', sa.Enum('MANUAL', 'AUTOMATICA', name='transmision'), nullable=False),
    sa.Column('combustible', sa.Enum('GASOLINA', 'DIESEL', 'HIBRIDO', 'ELECTRICO', 'GAS', name='combustible'), nullable=False),
    sa.Column('carroceria', sa.Enum('SEDAN', 'HATCHBACK', 'SUV', 'PICKUP', 'CAMIONETA', 'VAN', name='carroceria'), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('puertas', sa.Integer(), nullable=False),
    sa.Column('cilindraje', sa.Integer(), nullable=False),
    sa.Column('traccion', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('placa_termina_en', sa.Integer(), nullable=True),
    sa.Column('origen', sa.Enum('PROPIO', 'CONSIGNACION', name='origen'), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'RESERVADO', 'VENDIDO', name='estadovehiculo'), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('caracteristicas', sa.JSON(), nullable=True),
    sa.Column('imagenes', sa.JSON(), nullable=True),
    sa.Column('publicado_en', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiculos_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculos_destacado'), ['destacado'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculos_marca'), ['marca'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculos_origen'), ['origen'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculos_precio'), ['precio'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculos_publicado_en'), ['publicado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculos_slug'), ['slug'], unique=True)

    op.create_table('simulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('cuota_inicial', sa.Integer(), nullable=False),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('tasa_mensual', sa.Float(), nullable=False),
    sa.Column('monto_financiado', sa.Integer(), nullable=False),
    sa.Column('cuota_mensual', sa.Integer(), nullable=False),
    sa.Column('total_a_pagar', sa.Integer(), nullable=False),
    sa.Column('total_intereses', sa.Integer(), nullable=False),
    sa.Column('vehiculo_slug', sqlmodel.sql.sqltypes.AutoString(length=140), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulaciones_creado_en'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulaciones_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulaciones_vehiculo_slug'), ['vehiculo_slug'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulaciones_vehiculo_slug'))
        batch_op.drop_index(batch_op.f('ix_simulaciones_lead_id'))
        batch_op.drop_index(batch_op.f('ix_simulaciones_creado_en'))

    op.drop_table('simulaciones')
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculos_slug'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_publicado_en'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_precio'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_origen'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_marca'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_estado'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_destacado'))
        batch_op.drop_index(batch_op.f('ix_vehiculos_anio'))

    op.drop_table('vehiculos')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_vehiculo_slug'))
        batch_op.drop_index(batch_op.f('ix_leads_tipo'))
        batch_op.drop_index(batch_op.f('ix_leads_telefono'))
        batch_op.drop_index(batch_op.f('ix_leads_estado'))
        batch_op.drop_index(batch_op.f('ix_leads_creado_en'))

    op.drop_table('leads')
    # ### end Alembic commands ###
